Makefile : 01-three-words/01-three-words.cc 02-divisors-in-order/02-divisors-in-order.cc 03-prime-number/03-prime-number.cc 04-looking-for-an-a/04-looking-for-an-a.cc 05-hamonic-numbers/05-hamonic-numbers.cc 06-harmonic-numbers-2/06-harmonic-numbers-2.cc 07-first-position/07-first-position.cc 08-i-thv/08-i-th.cc 09-approximate-e/09-approximate-e.cc 10-Parentheses/10-Parentheses.cc 
	gcc -o 01-three-words/01-three-words 01-three-words/01-three-words.cc
	gcc -o 03-prime-number/03-prime-number 03-prime-number/03-prime-number.cc
	gcc -o 02-divisors-in-order/02-divisors-in-order 02-divisors-in-order/02-divisors-in-order.cc 
	gcc -o 04-looking-for-an-a/04-looking-for-an-a 04-looking-for-an-a/04-looking-for-an-a.cc
	gcc -o 05-hamonic-numbers/05-hamonic-numbers 05-hamonic-numbers/05-hamonic-numbers.cc
	gcc -o 06-harmonic-numbers-2/06-harmonic-numbers-2 06-harmonic-numbers-2/06-harmonic-numbers-2.cc
	gcc -o 07-first-position/07-first-position 07-first-position/07-first-position.cc
	gcc -o 08-i-thv/08-i-th 08-i-thv/08-i-th.cc
	gcc -o 09-approximate-e/09-approximate-e 09-approximate-e/09-approximate-e.cc
	gcc -o 10-Parentheses/10-Parentheses 10-Parentheses/10-Parentheses.cc

clean :
	rm  01-three-words/01-three-words 01-three-words/01-three-words.cc
	rm  03-prime-number/03-prime-number 03-prime-number/03-prime-number.cc
	rm  02-divisors-in-order/02-divisors-in-order 02-divisors-in-order/02-divisors-in-order.cc 
	rm  04-looking-for-an-a/04-looking-for-an-a 04-looking-for-an-a/04-looking-for-an-a.cc
	rm  05-hamonic-numbers/05-hamonic-numbers 05-hamonic-numbers/05-hamonic-numbers.cc
	rm  06-harmonic-numbers-2/06-harmonic-numbers-2 06-harmonic-numbers-2/06-harmonic-numbers-2.cc
	rm  07-first-position/07-first-position 07-first-position/07-first-position.cc
	rm  08-i-thv/08-i-th 08-i-thv/08-i-th.cc
	rm  09-approximate-e/09-approximate-e 09-approximate-e/09-approximate-e.cc
	rm  10-Parentheses/10-Parentheses 10-Parentheses/10-Parentheses.cc
